earliest_year_filter: "2017"
columns_to_encode: 
  - "Payments made in the reporting period"
  - "Participates in payment codes"
  - "E-Invoicing offered"
  - "Supply-chain financing offered"
  - "Policy covers charges for remaining on supplier list"
  - "Charges have been made for remaining on supplier list"
  - "Payment terms have changed"
  - "Suppliers notified of changes"

column_one: "Payment terms have changed"
column_two: "Suppliers notified of changes"

inflation_rate_data_start_date: '2017-01-01'

columns_to_convert_from_float_to_integers:
  - "Payments made in the reporting period"
  - "Average time to pay"
  - "Shortest (or only) standard payment period"
  - "Longest standard payment period"
  - "Maximum contractual payment period"
  - "Payment terms have changed"
  - "Suppliers notified of changes"
  - "Participates in payment codes"
  - "E-Invoicing offered"
  - "Supply-chain financing offered"
  - "Policy covers charges for remaining on supplier list"
  - "Charges have been made for remaining on supplier list"

columns_to_exclude_for_imputation: 'Period'

columns_to_include_for_robust_scaling: '% Invoices not paid within agreed terms'
column_for_clustering: '% Invoices not paid within agreed terms'
number_of_components_to_retain: 10



### ML

target: 'Risk Level'
columns_to_exclude: 'Period'

# Model names
decision_tree: 'Decision Tree'
logistic_regression: 'Logistic Regression'
svm: 'Support Vector Machine'
ann: 'Artificial Neural Network'
probit: 'Probit'


### Hyperparameter optimisation 

number_of_iterations_randomised_search: 100

number_of_iterations_randomised_search_decision_tree: 100

#rfe
number_of_features_to_select: 99 # 99


period: "Period"


split_num: 10
