earliest_year_filter: "2017"
columns_to_encode: 
  - "Payments made in the reporting period"
  - "Participates in payment codes"
  - "E-Invoicing offered"
  - "Supply-chain financing offered"
  - "Policy covers charges for remaining on supplier list"
  - "Charges have been made for remaining on supplier list"
  - "Payment terms have changed"
  - "Suppliers notified of changes"

column_one: "Payment terms have changed"
column_two: "Suppliers notified of changes"

inflation_rate_data_start_date: '2017-01-01'